name: Check and Update flake.nix AppImage Version

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  check-flake-version:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cachix/devenv:latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest release version from GitHub
        id: get_latest_version
        run: |
          nix shell nixpkgs#jq nixpkgs#curl -c '
            LATEST=$(curl -s https://api.github.com/repos/Highl1te/HighliteDesktop/releases/latest | jq -r .tag_name)
            VERSION=${LATEST#v}
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          '

      - name: Check flake.nix for correct version
        id: check_version
        run: |
          if grep -q "version = \"${VERSION}\";" flake.nix; then
            echo "Up to date"
            echo "needs_update=false" >> $GITHUB_ENV
          else
            echo "flake.nix does not reference the current AppImage version: $VERSION"
            echo "needs_update=true" >> $GITHUB_ENV
          fi

      - name: Update flake.nix with new version and sha256
        if: env.needs_update == 'true'
        run: |
          URL="https://github.com/Highl1te/HighliteDesktop/releases/download/v${VERSION}/HighLite-${VERSION}.AppImage"
          nix shell nixpkgs#nix-prefetch-url nixpkgs#gnused -c '
            SHA256=$(nix-prefetch-url --type sha256 "$URL")
            sed -i "s/version = \".*\";/version = \"${VERSION}\";/" flake.nix
            sed -i "s|sha256 = \".*\";|sha256 = \"${SHA256}\";|" flake.nix
          '

      - name: Commit and push changes
        if: env.needs_update == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add flake.nix
          git commit -m "chore: update flake.nix to AppImage version ${VERSION}"
          git push
